### ISSUE TITLE
Issue or Question: how to know a cron is currently running

### ISSUE THREAD

**Issue by ochurlaud** [Cron/Cron#15]
I set my cronJobs during the initialization of the app (one has to go to `myapp/install`)

I would like to know: how can I be sure that the cronJob has been set and is running, in case someone goes again to `myapp/install` ?

```
sudo -u php -H crontab -l 
```
is empty....

**Comment by NoUseFreak** [comment]
Hi,

This issue is indeed possible when allowing cron to be triggered from outside the server. If you can you should place a single trigger in your crontab. This way other can not trigger your cron more than you set it. 

If you want to make sure you do not run the same job in parallel, you can implement a basic Semaphore that logs/locks the jobs started an releases the job finished/failed.

Hope this answer was of any help.

**Comment by NoUseFreak** [comment]
Note: My implementation at the moment is an abstract of crontab. Crontab will have the same issue. 
I don't see any harm in providing a way for users to solve this problem from within the library.

**Comment by ochurlaud** [comment]
> If you can you should place a single trigger in your crontab

How do you do that ?

Do be sure not to write it twice I wanted to do a `$string =  exec(crontab -l)` and if the line exists, skip the creation of the crontab, else write it.

I must say that I'm a little confused about your answer: should my `crontab -l` with php user return something?

**Comment by NoUseFreak** [comment]
Your (unix) crontab should have something like:

```
* * * * * php /path/to/cron.php >/dev/null 2>&1
```

Inside the `cron.php` file you initialize the app and trigger the `$cron->run()` as the example in the readme. 
To do this you will probably move your bootstrap code in a separate file and include it in both the `webapp` and the `cron.php`.

**Comment by ochurlaud** [comment]
Ok, maybe I didn't get the purpose of your bundle. What I wanted is that no one has to create a cronjob by hand: everything should be done by the website itself... 

I finally ran 4 exec() to let php create the cron itself...

**Comment by NoUseFreak** [comment]
Indeed, the library works the other way around. You create one unix cronjob to trigger the library. The library will allow your application to decide when and what jobs are executed.
