### ISSUE TITLE
My script does not work

### ISSUE THREAD

**Issue by bonaccorsop** [Cron/Cron#16]
I'm using "cron/cron": "1.0.5".
I wrote the following code inside a script callable by cli:

```
        $job1 = new \Cron\Job\ShellJob();
        $job1->setCommand('touch myfile');
        $job1->setSchedule(new \Cron\Schedule\CrontabSchedule('* * * * *'));

        $resolver = new \Cron\Resolver\ArrayResolver();
        $resolver->addJob($job1);

        $cron = new \Cron\Cron();
        $cron->setExecutor(new \Cron\Executor\Executor());
        $cron->setResolver($resolver);

        $report = $cron->run();
```

I run this script in cli (also with root user) and nothing seems to happened (I expect to see myfile).

So I decided to dump the job output

```
foreach ($report->getReports() as $jobReport) {
     var_dump($jobReport->isSuccessful(), $jobReport->getOutput());
}
```

and the result of this dump is:

```
NULL
array(0) {
}
```

I don't think to do something wrong, also because I copied and pasted the example in the doc.

Have you any idea about my issue?

**Comment by NoUseFreak** [comment]
If you want to process the output you will need to wait for the jobs to finish.

Before looping over the reports place the following:

```php
        while ($cron->isRunning()) {
            usleep(100);
        }
```

Hope it fixes your problem.

**Comment by bonaccorsop** [comment]
Yes, seems that the cron died with the php parent process. This fixes this problem
