### ISSUE TITLE
Improvement ideas

### ISSUE THREAD

**Issue by sagikazarmark** [Cron/Cron#18]
I was recently developping a cron package just like yours. I usually implement everything that I need and look around afterwards and see how existing implementations compare to that.

Your library and my needs (what I have done so far) are pretty much the same, but there are a few differences, so I wanted to reach you out and ask if you are open to my suggestions. If yes, I am happy to provide a PR with all the changes.

Actually most of them contains some workflow/package quality related concerns.

## Use Michael Dowling's Cron expression engine

I can't really say anything about it. Are there any particular reasons why you implemented your own pattern matcher?

## Remove interface suffix

This is something that I asked in case of many-many libraries with fear, because I don't like messing with authors personal preferences, but in most cases people welcomed my proposal. Interface suffixes is not PHP specific, unfortunately it is present in many other languages as well.

I usually link Mathias Verraes's blog post about this topic because he lists every argument against interface suffixes.

http://verraes.net/2013/09/sensible-interfaces/

My opinion is that it makes the library more readable from a programmer point of view. The lazy ones, how doesn't care about reading source code (and neither docs in most cases), just want to use it would say otherwise.

## Separate spec and integration tests

PHPUnit is great, but spec testing is simply better to make sure your code behaves exactly you want. So I usually suggest writting spec tests for code (where possible). In a builder like context (like this is) it is absolutely possible. Looking at the external dependencies, mocking is also possible.

## Add job queue plugin (async executor)

In some cases long running tasks can overlap. This is my biggest problem with most cron runners. In these cases a queue would be a good choice, where only one job is executed at a time and the others wait for it (and are not getting lost)

Of course this should be plugin, not part of the main package.

## Extract shell job to a separate package

It is always a good idea in case of pluggable systems like this, to extract as many components as possible, so that the main package can provide a stable contract with as less changing part (aka. interfaces, code that is possibly not changing, like exceptions, main entry points for plugins, etc) as possible.

## Event reporters

I would consider converting the reporters to an event-driven logic. That would allow other tasks (like logging). What do you think?

I think that all the point above improves the project's general quality. What do you think?

**Comment by NoUseFreak** [comment]
Hi,

Thanks for reviewing the library. I think you have some great proposals. 

I made independent issues of your feedback.
