### ISSUE TITLE
Use Michael Dowling's Cron expression engine

### ISSUE THREAD

**Issue by NoUseFreak** [Cron/Cron#20]
I can't really say anything about it. Are there any particular reasons why you implemented your own pattern matcher?

Split from #18

**Comment by NoUseFreak** [comment]
No specific reason why I wrote it by myself. I must admit I did not know this library existed. It would indeed be a good alternative to my self-written implementation.

**Comment by sagikazarmark** [comment]
I think it is good enough. Also, I think multiple pattern matchers do not really make sense, since there is only one way which you can parse cron expressions.
