### ISSUE TITLE
Separate spec and integration tests

### ISSUE THREAD

**Issue by NoUseFreak** [Cron/Cron#22]
PHPUnit is great, but spec testing is simply better to make sure your code behaves exactly you want. So I usually suggest writting spec tests for code (where possible). In a builder like context (like this is) it is absolutely possible. Looking at the external dependencies, mocking is also possible.

Split from #18

**Comment by NoUseFreak** [comment]
Here I am confused. I don't see how you want to implement this. Currently parts of the library already have integration tests.

**Comment by sagikazarmark** [comment]
There are two types of tests:

1. Specification test: when you test parts of your code separately with some kind of test data to ensure your object behaves like you expect. (Usually testing that getters/setters does what they should do)
2. Integration test: When you test your code as a whole with some kind of real life example data to ensure it actually works.

In PHPUnit you have the two together. With a phpspec+behat combo you can have the two separated which allows you to test your code from two point of view.
