### ISSUE TITLE
Add job queue plugin (async executor)

### ISSUE THREAD

**Issue by NoUseFreak** [Cron/Cron#23]
In some cases long running tasks can overlap. This is my biggest problem with most cron runners. In these cases a queue would be a good choice, where only one job is executed at a time and the others wait for it (and are not getting lost)

Of course this should be plugin, not part of the main package.

Split from #18

**Comment by NoUseFreak** [comment]
I have been thinking about this as well but came to the conclusion this would in fact be a background worker. 

I see a cron more as an action that needs to run every x and the runtime should not be a problem. 
The timing problem can be solved with a queue/worker approach.

**Comment by sagikazarmark** [comment]
In this case the action would be passing the job to the queue. But you are right, this is a queue/worker approach, never suggested it isn't.
