### ISSUE TITLE
Extract shell job to a separate package

### ISSUE THREAD

**Issue by NoUseFreak** [Cron/Cron#24]
It is always a good idea in case of pluggable systems like this, to extract as many components as possible, so that the main package can provide a stable contract with as less changing part (aka. interfaces, code that is possibly not changing, like exceptions, main entry points for plugins, etc) as possible.

Split from #18

**Comment by NoUseFreak** [comment]
Indeed this should be a separate package. Note that splitting these now would require increasing the major version number. (unless it will be required by the main project)

**Comment by sagikazarmark** [comment]
You can do the same as in case of the interfaces: create the separate package, but don't remove the old code until the next major version. The two can live together I think, but you need to have a separate namespace for the plugin which you should have anyway.
