### ISSUE TITLE
Need to wait for processes to stop (call job->wait())

### ISSUE THREAD

**Issue by sucotronic** [Cron/Cron#42]
I tried the example of the Readme, and I've found that the main thread should wait for its children to finish, because if not, the children get killed at the end of the parent.

I've done a workaround extending the ShellJob class to wait them:

```
class FixShellJob extends \Cron\Job\ShellJob
{
    public function run(\Cron\Report\JobReport $report)
    {
        $this->report = $report;
        $report->setStartTime(microtime(true));
        $process = $this->getProcess();
        $process->start(function ($type, $buffer) use ($report) {
            if (Process::ERR === $type) {
                $report->addError($buffer);
            } else {
                $report->addOutput($buffer);
            }
        });
        // FIXME this is necessary to not be killed when parent thread ends
        $process->wait();
    }
}

$job1 = new FixShellJob();
$job1->setCommand('touch /tmp/test');
$job1->setSchedule(new \Cron\Schedule\CrontabSchedule('* * * * *'));
```

In the Symfony Process doc it mentions that when running asynchronously, you can do more stuff, but you should wait  for the children to finish before finishing the parent: http://symfony.com/doc/current/components/process.html#running-processes-asynchronously

**Comment by sucotronic** [comment]
Well, maybe this is "documentation issue" instead of a coding issue, because I've found a nicer way to wait for processes to end:

```
$report = $cron->run();
foreach($jobs as $job)
    while($job->isRunning())
        sleep(1);
```

**Comment by NoUseFreak** [comment]
Hi,

Sorry for the late response.
Good to hear you found the solution. 

Feel free to create a PR. 

I think you can also do the following:

```php
while ($cron->isRunning()) {
    sleep(1);
}
```

**Comment by guyradford** [comment]
Hi 

The code snippet from @NoUseFreak didn't work for me. Based on another code snippet I got this to work:

```php
        // this waits until all the jobs have finished
        $report = $cron->run();
        foreach( $report->getReports() as $report)
//            $job = $report->getJob();
            while($report->getJob()->isRunning())
                $report->getJob()->getProcess()->wait();

```
