### ISSUE TITLE
Weekday "7" not accepted

### ISSUE THREAD

**Issue by piwi91** [Cron/Cron#43]
I try to use "Sunday" as weekday "7" but this isn't accepted. According to the documentation this is a valid value but an exception is thrown.
What is correct? The documentation or the exception?

**Comment by NoUseFreak** [comment]
It should work as documented. If not this issue will be accepted and open for anyone to solve.

**Comment by piwi91** [comment]
Changed a test (checkout https://github.com/piwi91/Cron/commit/9f1cdb6a39be3ee6112d3eab4a79cbb9ad90fb50)
Then run the PHPUnit test suite

Result:

```
PHPUnit 4.8.31 by Sebastian Bergmann and contributors.

...............E...............................................  63 / 165 ( 38%)
............................................................... 126 / 165 ( 76%)
.......................................

Time: 267 ms, Memory: 6.50MB

There was 1 error:

1) Cron\CronTest::testNewExample
Cron\Exception\InvalidPatternException: Invalid day of week "7".

/home/administrator/projects/Cron/src/Validator/CrontabValidator.php:74
/home/administrator/projects/Cron/src/Schedule/CrontabSchedule.php:189
/home/administrator/projects/Cron/src/Schedule/CrontabSchedule.php:54
/home/administrator/projects/Cron/tests/CronTest.php:104
```

**Comment by piwi91** [comment]
We can close this ticket because it's fixed.
