### ISSUE TITLE
Create a way to trigger other php functions

### ISSUE THREAD

**Issue by NoUseFreak** [Cron/Cron#5]
Add a PhpJob to trigger function calls. These calls should be executed in a different thread so when the main script finishes, the called function can keep running.

@TjorvenB @RustiSub @bdaenen Any ideas or suggestions?

**Comment by Progi1984** [comment]
Hi @NoUseFreak, How is it possible to launch static methods from a job ?

**Comment by NoUseFreak** [comment]
At the moment Cron uses the `symfony/process'`s `PhpProcess` internally.
This only takes a script string. It should be possible to create a script containing the static call.

I currently don't see how the library itself can provide this because bootstrapping the application can be different.

If you have a proposal I would love to hear it.

**Comment by Progi1984** [comment]
@NoUseFreak Yes, I thought good that is the only idea.

May be use a [call_user_func](http://php.net/manual/fr/function.call-user-func.php) ?

**Comment by NoUseFreak** [comment]
I understand you can call `call_user_func`. But I am not quite sure how the applicatoin would bootstrap itself from this call. ex. instantiate a database connection. Are all these responsibilities for this one static call?
