### ISSUE TITLE
Question: Removing & Adding Jobs

### ISSUE THREAD

**Issue by xemose** [Cron/Cron#55]
I'm very interested in using this library to schedule jobs for my job processing library. However, I had three very important questions.

### **1. Consider the following:**
The command, `$cron->run();`, is running in the background using Cron.

Question:
If this is the case then can you add a job to Cron from a different file? Such as having another class add a job using the following code:
```
$job1 = new \Cron\Job\ShellJob();
$job1->setCommand('ls -la /path/to/folder');
$job1->setSchedule(new \Cron\Schedule\CrontabSchedule('*/5 * * * *'));
```

### **2. Consider the following:**
Environment is same as question 1.

Question:
If there is a job added to execute every 1 minute, how would one remove the job from the execution list?

### **3. If you wanted to run a worker to execute the library in the background every 5 seconds, is the following code sufficient enough?**

```php
<?php

require_once(__DIR__ . '/vendor/autoload.php');

$cron = new \Cron\Cron();
$cron->setExecutor(new \Cron\Executor\Executor());
$cron->setResolver($resolver);

$cron->run();
```

Thank you in advanced for all your help!

**Comment by NoUseFreak** [comment]
1. The `$cron-run()` is a longrunning process so should not be in your system cron
2. By settings the schedule to `* * * * *` it will start the job every minute.
3. Cron currently only supports scheduling to the minute. (Trying to not diverge from the system cron functionality)

**Comment by NoUseFreak** [comment]
Please reopen if you need more info.
