### ISSUE TITLE
Cron and the time zone

### ISSUE THREAD

**Issue by Soimil** [Cron/Cron#70]
Hello, 
Is it possible to set the time zone against which the cron pattern will be checked?
If not, will it be added in subsequent versions?

For example to be possible set some like this:
`5 2 3 * * TZ="America/New_York" /do/command > /dev/null 2>&1`

Thanks

**Comment by wouter-toppy** [comment]
Created a pull: https://github.com/Cron/Cron/pull/77

Usage:
`0 */3 * * * TZ="Europe/Amsterdam" /var/command > /dev/null 2>&1`

**Comment by wouter-toppy** [comment]
@NoUseFreak  could you take a look at this?
