### ISSUE TITLE
i gave this syntax for cron "17 17 18 2 5" but didnt execute my fucntion at that time, but "* * * * *" this one is working 

### ISSUE THREAD

**Issue by nettemsarath** [Cron/Cron#75]
var CronJob = require("cron").CronJob;

const SendEmail = (payload) => {
  console.log("SENDING EMAIL", payload);
};

const ScheduleCronJob = (payload, cronTime) => {
  console.log("ScheduleCronJob.........", cronTime);
  const job = new CronJob(cronTime, () => {
    console.log("You will see this message every second");
    SendEmail(payload);
    job.stop();
  });
  return job;
};
const payload = { name: "sarath" };
const job = ScheduleCronJob(payload, "17 17 18 2 5");
job.start();

what it does is to  execute the function and stop it

**Comment by NoUseFreak** [comment]
Hi @nettemsarath, it might be related to timezones. The latest version has support for timezones.
